# Generated by Django 5.2 on 2026-09-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Supprimé le'),
        ),
    ]
