"""
Django settings for GestionRDV project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ==========================================================================
# Environnement
# ==========================================================================
# Toute la configuration sensible (secrets, hôtes autorisés, base de
# données) est chargée depuis l'environnement (fichier .env en local,
# variables d'environnement réelles en production) — aucune valeur
# sensible n'est codée en dur dans ce fichier.

env = environ.Env(
    DEBUG=(bool, False),
)
environ.Env.read_env(BASE_DIR / ".env")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "users.apps.UsersConfig",
    "rdv",
    "django_celery_beat",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "users.middleware.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "GestionRDV.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "GestionRDV.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Chargée depuis DATABASE_URL (ex: postgres://user:pass@host:port/dbname).
# En son absence (développement local sans Postgres), on retombe sur SQLite.
_default_sqlite_url = f"sqlite:///{(BASE_DIR / 'db.sqlite3').as_posix()}"
_database_url = env("DATABASE_URL", default="")

DATABASES = {
    "default": env.db_url_config(_database_url or _default_sqlite_url),
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "fr-fr"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = 'users.Utilisateur'

LOGIN_URL = '/users/login'
LOGIN_REDIRECT_URL = '/users/dashboard/'
LOGOUT_REDIRECT_URL = '/users/connexion/'

NOTIFY_SEND_EMAIL = False
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'no-reply@localhost'


CELERY_BROKER_URL = env("CELERY_BROKER_URL", default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND", default='redis://localhost:6379/1')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC = True

# Planning des tâches périodiques (rdv/tasks.py). Le service "beat" de
# docker-compose.yml tourne déjà avec --scheduler
# django_celery_beat.schedulers:DatabaseScheduler ; ce scheduler relit
# CELERY_BEAT_SCHEDULE à chaque démarrage (DatabaseScheduler.setup_schedule
# -> update_from_dict) et synchronise automatiquement les entrées dans la
# base (table PeriodicTask) — aucune modification de docker-compose.yml
# n'est nécessaire pour que ce planning prenne effet.
#
# La fréquence de chaque tâche est dictée par la fenêtre de temps qu'elle
# interroge : une tâche à fenêtre étroite ET sans rattrapage (elle ne
# revérifie jamais le passé) doit tourner au moins aussi souvent que sa
# fenêtre est large, sous peine de rater définitivement des cas tombés
# entre deux exécutions. Une tâche à seuil ouvert (elle traite tout ce qui
# est "avant maintenant", sans limite basse) ne rate jamais rien : espacer
# ses exécutions ne fait qu'ajouter du délai, pas de perte.
CELERY_BEAT_SCHEDULE = {
    # Fenêtre étroite et sans rattrapage : auto_start_rdv ne regarde que
    # [maintenant, maintenant+5min[. Au-delà de 5 min entre deux exécutions,
    # un RDV confirmé pourrait traverser toute la fenêtre sans qu'aucune
    # exécution ne le voie (la requête suivante a un "maintenant" déjà
    # passé cette date, donc `date_heure_rdv__gte=now` l'exclut pour
    # toujours). 2 min laisse une marge de sécurité contre la latence
    # d'exécution des tâches précédentes.
    'auto-start-rdv': {
        'task': 'rdv.tasks.auto_start_rdv',
        'schedule': timedelta(minutes=2),
    },
    # Fenêtre étroite et sans rattrapage : send_rdv_reminder_24h ne regarde
    # que [demain-15min, demain+15min] (30 min de large). Toutes les
    # 15 min, les fenêtres successives se touchent sans laisser de trou
    # (l'une finit exactement où la suivante commence), garantissant
    # qu'aucun RDV ne traverse la fenêtre entre deux exécutions.
    'send-rdv-reminder-24h': {
        'task': 'rdv.tasks.send_rdv_reminder_24h',
        'schedule': timedelta(minutes=15),
    },
    # Seuil ouvert, pas de fenêtre à couvrir : auto_cancel_expired_rdv
    # traite tout RDV programmé/reporté de plus de 2h (sans limite basse),
    # donc jamais raté, seulement traité plus tard si l'espacement est
    # grand. 30 min borne le délai d'annulation automatique sans solliciter
    # la base plus souvent que nécessaire pour une tâche non urgente.
    'auto-cancel-expired-rdv': {
        'task': 'rdv.tasks.auto_cancel_expired_rdv',
        'schedule': timedelta(minutes=30),
    },
    # Seuil ouvert, même raisonnement : expire_old_waitlist_entries traite
    # toute inscription dont date_expiration est passée, sans limite basse.
    # Une cadence horaire suffit, une liste d'attente n'étant pas aussi
    # chronosensible qu'un rappel de rendez-vous.
    'expire-old-waitlist-entries': {
        'task': 'rdv.tasks.expire_old_waitlist_entries',
        'schedule': timedelta(hours=1),
    },
}


# ==========================================================================
# Durcissement production
# ==========================================================================
# Ces réglages ne s'activent qu'en dehors du mode DEBUG (donc en
# production, où DEBUG doit toujours valoir False). Ils sont eux aussi
# ajustables via l'environnement pour s'adapter à l'infrastructure réelle
# (ex: terminaison TLS faite par un reverse proxy en amont).
if not DEBUG:
    SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = env.int("SECURE_HSTS_SECONDS", default=31536000)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
