# Generated by Django 5.2 on 2025-06-18 10:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Medecin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_order", models.CharField(blank=True, max_length=20)),
                (
                    "specialite",
                    models.CharField(
                        choices=[
                            ("generaliste", "Médecin Généraliste"),
                            ("cardiologue", "Cardiologue"),
                            ("dermatologue", "Dermatologue"),
                            ("pediatre", "Pédiatre"),
                            ("gynécologue", "Gynécologue"),
                            ("neurologue", "Neurologue"),
                            ("psychiatre", "Psychiatre"),
                            ("orthopediste", "Orthopédiste"),
                            ("ophtalmologue", "Ophtalmologue"),
                            ("orl", "ORL"),
                        ],
                        max_length=100,
                    ),
                ),
                ("cabinet", models.CharField(blank=True, max_length=200)),
                ("adresse_cabinet", models.TextField(blank=True)),
                (
                    "tel",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Numéro de téléphone invalide",
                                regex="^\\+?[0-9\\s\\-\\(\\)]+$",
                            )
                        ],
                    ),
                ),
                (
                    "sexe",
                    models.CharField(
                        choices=[("F", "Féminin"), ("M", "Masculin")],
                        default="F",
                        max_length=10,
                    ),
                ),
                ("diplomes", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profil_medecin",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Médecin",
                "verbose_name_plural": "Médecins",
            },
        ),
        migrations.CreateModel(
            name="Disponibilite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jour", models.CharField(max_length=15)),
                ("heure_debut", models.TimeField()),
                ("heure_fin", models.TimeField()),
                (
                    "medecin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rdv.medecin"
                    ),
                ),
            ],
            options={
                "verbose_name": "Disponibilité",
                "verbose_name_plural": "Disponibilités",
            },
        ),
        migrations.CreateModel(
            name="MessageBot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenu", models.TextField()),
                ("intention", models.CharField(max_length=200)),
                ("reponse", models.TextField()),
                ("date_echange", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Message du ChatBot",
                "verbose_name_plural": "Messages du ChatBot",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("type", models.CharField(max_length=20)),
                ("date_envoi", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_patient",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                ("date_naissance", models.DateField()),
                ("adresse", models.TextField(blank=True)),
                (
                    "sexe",
                    models.CharField(
                        choices=[("F", "Féminin"), ("M", "Masculin")],
                        default="F",
                        max_length=10,
                    ),
                ),
                (
                    "tel",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Numéro de téléphone invalide",
                                regex="^\\+?[0-9\\s\\-\\(\\)]+$",
                            )
                        ],
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profil_patient",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
            },
        ),
        migrations.CreateModel(
            name="RendezVous",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_heure_rdv", models.DateTimeField()),
                ("motif", models.CharField(blank=True, max_length=200)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("programme", "Programmé"),
                            ("confirme", "Confirmé"),
                            ("en_cours", "En cours"),
                            ("termine", "Terminé"),
                            ("annule", "Annulé"),
                            ("reporte", "Reporté"),
                        ],
                        default="programme",
                        max_length=20,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now_add=True)),
                (
                    "medecin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rendez_vous",
                        to="rdv.medecin",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rendez_vous",
                        to="rdv.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rendez-Vous",
                "verbose_name_plural": "Rendez-Vous",
            },
        ),
    ]
