# Generated by Django 5.2 on 2026-03-29 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(blank=True, choices=[('mon', 'Lundi'), ('tue', 'Mardi'), ('wed', 'Mercredi'), ('thu', 'Jeudi'), ('fri', 'Vendredi'), ('sat', 'Samedi'), ('sun', 'Dimanche')], help_text='Jour de la semaine (pour disponibilités récurrentes)', max_length=3)),
                ('date_specific', models.DateField(blank=True, help_text='Date précise (pour congés ou cas particulier)', null=True)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('is_active', models.BooleanField(default=True, help_text='Désactive pour masquer temporairement sans supprimer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Disponibilité',
                'verbose_name_plural': 'Disponibilités',
                'ordering': ['medecin', 'date_specific', 'jour', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='FavoriMedecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_order', models.CharField(blank=True, max_length=20)),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('specialite', models.CharField(choices=[('generaliste', 'Médecin Généraliste'), ('cardiologue', 'Cardiologue'), ('dermatologue', 'Dermatologue'), ('pediatre', 'Pédiatre'), ('gynecologue', 'Gynécologue'), ('neurologue', 'Neurologue'), ('psychiatre', 'Psychiatre'), ('orthopediste', 'Orthopédiste'), ('ophtalmologue', 'Ophtalmologue'), ('orl', 'ORL')], max_length=100)),
                ('cabinet', models.CharField(blank=True, max_length=200)),
                ('adresse_cabinet', models.TextField(blank=True)),
                ('tel', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide', regex='^\\+?[0-9\\s\\-\\(\\)]+$')])),
                ('sexe', models.CharField(choices=[('F', 'Féminin'), ('M', 'Masculin')], default='F', max_length=10)),
                ('diplomes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='medecins/')),
                ('tarif_consultation', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('langues_parlees', models.CharField(blank=True, help_text='Ex: Français, Anglais, Arabe', max_length=200)),
                ('accepte_nouveaux_patients', models.BooleanField(default=True)),
                ('delai_moyen_rdv', models.IntegerField(blank=True, help_text='En jours', null=True)),
            ],
            options={
                'verbose_name': 'Médecin',
                'verbose_name_plural': 'Médecins',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('info', 'Information'), ('success', 'Succès'), ('warning', 'Alerte'), ('error', 'Erreur')], default='info', max_length=50)),
                ('category', models.CharField(choices=[('appointment', 'Rendez-vous'), ('system', 'Système'), ('profile', 'Profil'), ('reminder', 'Rappel')], default='system', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('date_read', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_patient', models.CharField(blank=True, max_length=20, unique=True)),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('adresse', models.TextField(blank=True)),
                ('sexe', models.CharField(choices=[('F', 'Féminin'), ('M', 'Masculin')], default='F', max_length=10)),
                ('tel', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide', regex='^\\+?[0-9\\s\\-\\(\\)]+$')])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='patients/')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
        migrations.CreateModel(
            name='RdvHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Création'), ('confirm', 'Confirmation'), ('cancel', 'Annulation'), ('report', 'Report'), ('update', 'Mise à jour'), ('delete', 'Suppression')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'verbose_name': 'Historique RDV',
                'verbose_name_plural': 'Historique RDV',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RechercheSymptome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptome', models.CharField(max_length=100)),
                ('specialites_suggerees', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure_rdv', models.DateTimeField()),
                ('duree_minutes', models.IntegerField(default=30)),
                ('motif', models.CharField(blank=True, max_length=200)),
                ('statut', models.CharField(choices=[('programme', 'Programmé'), ('confirme', 'Confirmé'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé'), ('reporte', 'Reporté')], default='programme', max_length=20)),
                ('raison_report', models.CharField(blank=True, max_length=255, null=True)),
                ('raison_annulation', models.CharField(blank=True, max_length=255, null=True)),
                ('ancienne_date_heure', models.DateTimeField(blank=True, null=True)),
                ('report_initiator', models.CharField(blank=True, choices=[('medecin', 'Médecin'), ('patient', 'Patient')], help_text='Qui a initié le report', max_length=10, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rendez-Vous',
                'verbose_name_plural': 'Rendez-Vous',
            },
        ),
    ]
