# Generated by Django 5.2 on 2026-03-29 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rdv', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_medecin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favorimedecin',
            name='medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients_favoris', to='rdv.medecin'),
        ),
        migrations.AddField(
            model_name='disponibilite',
            name='medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='rdv.medecin'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favorimedecin',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medecins_favoris', to='rdv.patient'),
        ),
        migrations.AddField(
            model_name='rdvhistory',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rdv_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='recherchesymptome',
            index=models.Index(fields=['symptome'], name='rdv_recherc_symptom_605553_idx'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='rdv.medecin'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='rdv.patient'),
        ),
        migrations.AddField(
            model_name='rdvhistory',
            name='rdv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='rdv.rendezvous'),
        ),
        migrations.AddConstraint(
            model_name='disponibilite',
            constraint=models.UniqueConstraint(condition=models.Q(('date_specific__isnull', True), models.Q(('jour', ''), _negated=True)), fields=('medecin', 'jour', 'heure_debut', 'heure_fin'), name='unique_dispo_hebdo'),
        ),
        migrations.AddConstraint(
            model_name='disponibilite',
            constraint=models.UniqueConstraint(condition=models.Q(('jour', ''), ('jour__exact', ''), _connector='OR'), fields=('medecin', 'date_specific', 'heure_debut', 'heure_fin'), name='unique_dispo_specifique'),
        ),
        migrations.AlterUniqueTogether(
            name='favorimedecin',
            unique_together={('patient', 'medecin')},
        ),
    ]
