# Generated by Django 5.2 on 2025-06-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rdv", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rendezvous",
            name="duree_minutes",
            field=models.IntegerField(default=30),
        ),
    ]
