# Generated by Django 5.2 on 2025-06-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rdv", "0002_rendezvous_duree_minutes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medecin",
            name="specialite",
            field=models.CharField(
                choices=[
                    ("generaliste", "Médecin Généraliste"),
                    ("cardiologue", "Cardiologue"),
                    ("dermatologue", "Dermatologue"),
                    ("pediatre", "Pédiatre"),
                    ("gynecologue", "Gynécologue"),
                    ("neurologue", "Neurologue"),
                    ("psychiatre", "Psychiatre"),
                    ("orthopediste", "Orthopédiste"),
                    ("ophtalmologue", "Ophtalmologue"),
                    ("orl", "ORL"),
                ],
                max_length=100,
            ),
        ),
    ]
