# Generated by Django 5.2 on 2025-07-28 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rdv", "0003_alter_medecin_specialite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-date_envoi"],
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("appointment", "Rendez-vous"),
                    ("system", "Système"),
                    ("profile", "Profil"),
                    ("reminder", "Rappel"),
                ],
                default="system",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="date_read",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("info", "Information"),
                    ("success", "Succès"),
                    ("warning", "Alerte"),
                    ("error", "Erreur"),
                ],
                default="info",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
