# Generated by Django 5.2 on 2026-09-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0003_numeropatientcounter'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rendezvous',
            constraint=models.UniqueConstraint(condition=models.Q(('statut__in', ['programme', 'confirme'])), fields=('medecin', 'date_heure_rdv'), name='unique_rdv_actif_par_creneau'),
        ),
    ]
