# Generated by Django 5.2 on 2025-08-05 14:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rdv", "0004_alter_notification_options_notification_category_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="disponibilite",
            options={
                "ordering": ["medecin", "date_specific", "jour", "heure_debut"],
                "verbose_name": "Disponibilité",
                "verbose_name_plural": "Disponibilités",
            },
        ),
        migrations.AddField(
            model_name="disponibilite",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="disponibilite",
            name="date_specific",
            field=models.DateField(
                blank=True,
                help_text="Date précise (pour congés ou cas particulier)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="disponibilite",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Désactive pour masquer temporairement sans supprimer",
            ),
        ),
        migrations.AddField(
            model_name="disponibilite",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="disponibilite",
            name="jour",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mon", "Lundi"),
                    ("tue", "Mardi"),
                    ("wed", "Mercredi"),
                    ("thu", "Jeudi"),
                    ("fri", "Vendredi"),
                    ("sat", "Samedi"),
                    ("sun", "Dimanche"),
                ],
                help_text="Jour de la semaine (pour disponibilités récurrentes)",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="disponibilite",
            name="medecin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disponibilites",
                to="rdv.medecin",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="disponibilite",
            unique_together={
                ("medecin", "jour", "date_specific", "heure_debut", "heure_fin")
            },
        ),
    ]
