# Generated by Django 5.2 on 2026-09-09 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0004_rendezvous_unique_rdv_actif_par_creneau'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeAttenteCreneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure_souhaitee', models.DateTimeField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('notifie', 'Notifié'), ('expire', 'Expiré'), ('annule', 'Annulé'), ('honore', 'Honoré')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField(help_text="Passé ce moment sans avoir été honorée, l'inscription expire automatiquement.")),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liste_attente', to='rdv.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_liste_attente', to='rdv.patient')),
                ('rdv_propose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_liste_attente_honorees', to='rdv.rendezvous')),
            ],
            options={
                'verbose_name': "Inscription liste d'attente",
                'verbose_name_plural': "Inscriptions liste d'attente",
                'ordering': ['date_creation'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('statut', 'en_attente')), fields=('patient', 'medecin'), name='unique_inscription_active_par_patient_medecin')],
            },
        ),
    ]
