# Generated by Django 5.2 on 2025-08-05 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rdv", "0005_alter_disponibilite_options_disponibilite_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="disponibilite",
            options={
                "verbose_name": "Disponibilité",
                "verbose_name_plural": "Disponibilités",
            },
        ),
        migrations.AlterUniqueTogether(
            name="disponibilite",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="disponibilite",
            name="jour",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="disponibilite",
            name="medecin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rdv.medecin"
            ),
        ),
        migrations.RemoveField(
            model_name="disponibilite",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="disponibilite",
            name="date_specific",
        ),
        migrations.RemoveField(
            model_name="disponibilite",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="disponibilite",
            name="updated_at",
        ),
    ]
