# Generated by Django 5.2 on 2026-09-15 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0006_seed_recherche_symptome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdvhistory',
            name='rdv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='rdv.rendezvous'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rendez_vous', to='rdv.medecin'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rendez_vous', to='rdv.patient'),
        ),
    ]
