# Generated by Django 5.2 on 2025-08-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rdv", "0007_alter_disponibilite_options_disponibilite_created_at_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="disponibilite",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="disponibilite",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("date_specific__isnull", True),
                    models.Q(("jour", ""), _negated=True),
                ),
                fields=("medecin", "jour", "heure_debut", "heure_fin"),
                name="unique_dispo_hebdo",
            ),
        ),
        migrations.AddConstraint(
            model_name="disponibilite",
            constraint=models.UniqueConstraint(
                condition=models.Q(("jour", ""), ("jour__exact", ""), _connector="OR"),
                fields=("medecin", "date_specific", "heure_debut", "heure_fin"),
                name="unique_dispo_specifique",
            ),
        ),
    ]
