# Generated by Django 5.2 on 2025-08-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rdv", "0008_alter_disponibilite_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rendezvous",
            name="raison_annulation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="rendezvous",
            name="raison_report",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="rendezvous",
            name="date_modification",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
