# Generated by Django 5.2 on 2025-09-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rdv", "0009_rendezvous_raison_annulation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("appointment", "Rendez-vous"),
                    ("system", "Système"),
                    ("profile", "Profil"),
                    ("reminder", "Rappel"),
                ],
                default="system",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("info", "Information"),
                    ("success", "Succès"),
                    ("warning", "Alerte"),
                    ("error", "Erreur"),
                ],
                default="info",
                max_length=50,
            ),
        ),
    ]
