# Generated by Django 5.2 on 2025-09-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rdv", "0010_alter_notification_category_alter_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="rendezvous",
            name="ancienne_date_heure",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rendezvous",
            name="report_initiator",
            field=models.CharField(
                blank=True,
                choices=[("medecin", "Médecin"), ("patient", "Patient")],
                help_text="Qui a initié le report",
                max_length=10,
                null=True,
            ),
        ),
    ]
