# Generated by Django 5.2 on 2025-09-06 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rdv", "0011_rendezvous_ancienne_date_heure_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RdvHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Création"),
                            ("confirm", "Confirmation"),
                            ("cancel", "Annulation"),
                            ("report", "Report"),
                            ("update", "Mise à jour"),
                            ("delete", "Suppression"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("old_value", models.TextField(blank=True, null=True)),
                ("new_value", models.TextField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, null=True)),
                ("extra", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rdv_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rendez_vous",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="rdv.rendezvous",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique RDV",
                "verbose_name_plural": "Historique RDV",
                "ordering": ["-timestamp"],
            },
        ),
    ]
