# Generated by Django 5.2 on 2025-09-06 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rdv", "0012_rdvhistory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rdvhistory",
            old_name="reason",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="rdvhistory",
            old_name="rendez_vous",
            new_name="rdv",
        ),
    ]
