# Generated by Django 5.2 on 2025-09-14 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rdv", "0013_rename_reason_rdvhistory_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medecin",
            name="accepte_nouveaux_patients",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="medecin",
            name="delai_moyen_rdv",
            field=models.IntegerField(blank=True, help_text="En jours", null=True),
        ),
        migrations.AddField(
            model_name="medecin",
            name="langues_parlees",
            field=models.CharField(
                blank=True, help_text="Ex: Français, Anglais, Arabe", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="medecin",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="medecins/"),
        ),
        migrations.AddField(
            model_name="medecin",
            name="tarif_consultation",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="patients/"),
        ),
        migrations.CreateModel(
            name="RechercheSymptome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symptome", models.CharField(max_length=100)),
                ("specialites_suggerees", models.JSONField(default=list)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["symptome"], name="rdv_recherc_symptom_605553_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FavoriMedecin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
                (
                    "medecin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patients_favoris",
                        to="rdv.medecin",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medecins_favoris",
                        to="rdv.patient",
                    ),
                ),
            ],
            options={
                "unique_together": {("patient", "medecin")},
            },
        ),
    ]
